# Generated by Django 5.0 on 2023-12-26 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flatpages", "0001_initial"),
        ("lands", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutflatpage",
            name="page",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="about_flatepage",
                to="flatpages.flatpage",
            ),
        ),
        migrations.AlterField(
            model_name="contactflatpage",
            name="page",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_flatepage",
                to="flatpages.flatpage",
            ),
        ),
    ]
