# Generated by Django 5.0 on 2023-12-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lands", "0002_alter_aboutflatpage_page_alter_contactflatpage_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutflatpage",
            name="message",
            field=models.TextField(
                default="Your website is fully responsive so visitors can view your content from their choice of device.",
                max_length=1000,
            ),
        ),
    ]
