# Generated by Django 5.0 on 2023-12-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lands", "0003_aboutflatpage_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
    ]
