# Generated by Django 5.0 on 2023-12-26 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lands", "0005_alter_contact_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 12, 26, 15, 59, 22, 857508, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
