# Generated by Django 5.0 on 2023-12-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lands", "0006_contact_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("link", models.URLField(max_length=255)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("IG", "fa-instagram"),
                            ("FB", "fa-facebook-f"),
                            ("PIN", "fa-pinterest-p"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
