# Generated by Django 5.0 on 2023-12-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lands", "0007_sitesociallink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
            ],
        ),
    ]
