# Generated by Django 5.0 on 2023-12-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lands", "0008_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="TinymceApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=1000)),
            ],
        ),
    ]
