# Generated by Django 5.0 on 2023-12-28 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flatpages", "0001_initial"),
        ("lands", "0009_tinymceapikey"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page404Error",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_image", models.ImageField(upload_to="404/")),
                (
                    "page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="error_flatepage",
                        to="flatpages.flatpage",
                    ),
                ),
            ],
        ),
    ]
