# Generated by Django 5.0 on 2023-12-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_tag_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="bg_image",
            field=models.ImageField(
                default="file.jpg", upload_to="", verbose_name="posts/"
            ),
            preserve_default=False,
        ),
    ]
