# Generated by Django 5.0 on 2023-12-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_bg_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.IntegerField(default=0),
        ),
    ]
