# Generated by Django 5.0 on 2023-12-25 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_post_editor_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="editor_choice",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PostImageSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="post/slides/")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_postimageslides",
                        to="posts.post",
                    ),
                ),
            ],
        ),
    ]
