# Generated by Django 5.0 on 2023-12-26 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_post_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 12, 26, 15, 59, 34, 538531, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
