# Generated by Django 5.0 on 2023-12-26 20:45

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0013_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
