# Generated by Django 5.0 on 2023-12-27 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0014_alter_post_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"get_latest_by": "timestamp", "ordering": ("-timestamp", "pk")},
        ),
    ]
