# Generated by Django 5.0 on 2023-12-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0016_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("F_PODIUM", "fa-podium"),
                    ("F_ATOM", "fa-atom"),
                    ("F_USER_CHART", "fa-user-chart"),
                    ("F_TENNIS_BALL", "fa-tennis-ball"),
                    ("F_FLASK", "fa-flask"),
                    ("F_HEART", "fa-heart"),
                ],
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
