# Generated by Django 5.0 on 2024-01-01 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0017_alter_category_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="videos/"),
                ),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="video-upload/"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_videos",
                        to="posts.category",
                    ),
                ),
            ],
        ),
    ]
