# Generated by Django 5.0 on 2024-01-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0018_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="video",
        ),
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.URLField(default="http:127.0.0.1:8000", max_length=500),
            preserve_default=False,
        ),
    ]
