# Generated by Django 5.0 on 2023-12-26 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 12, 26, 9, 25, 19, 895958, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
