# Generated by Django 5.0 on 2023-12-26 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_myuser_date_joined"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.TextField(help_text="example facebook", max_length=100),
                ),
                ("link", models.URLField(max_length=255)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("IG", "Instagram"),
                            ("FB", "Facebook"),
                            ("TW", "Twitter"),
                            ("LD", "LinkedIn"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_social",
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
    ]
