# Generated by Django 5.0 on 2023-12-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_sociallink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="icon",
            field=models.CharField(
                choices=[
                    ("IG", "fa-instagram"),
                    ("FB", "fa-facebook-f"),
                    ("TW", "fa-twitter"),
                    ("LD", "fa-linkedin"),
                ],
                max_length=2,
            ),
        ),
    ]
