# Generated by Django 5.0 on 2023-12-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_sociallink_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(help_text="example facebook", max_length=100),
        ),
    ]
