# Generated by Django 5.0 on 2023-12-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_sociallink_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="cover/images/"),
        ),
    ]
