# Generated by Django 5.0 on 2023-12-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_profile_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="is_editor",
            field=models.BooleanField(default=False),
        ),
    ]
