# Generated by Django 5.0 on 2023-12-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_myuser_is_editor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                help_text="example facebook", max_length=100, unique=True
            ),
        ),
    ]
