# Generated by Django 5.0 on 2023-12-27 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100)),
                ("image", models.ImageField(upload_to="product/")),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "discount_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_product",
                        to="shop.shop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImageSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product/slides/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_image_slide",
                        to="shop.shop",
                    ),
                ),
            ],
        ),
    ]
