# Generated by Django 5.0 on 2023-12-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_product_productimageslide"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="items_in_stock",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
