# Generated by Django 5.0 on 2023-12-27 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_product_items_in_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reviews",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productimageslide",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_image_slide",
                to="shop.product",
            ),
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("review", models.TextField(max_length=200)),
                ("ratings", models.IntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_review",
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
