# Generated by Django 5.0 on 2023-12-27 14:17

import django.db.models.deletion
import django.views.generic.base
import lands.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0015_alter_post_options"),
        ("shop", "0005_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopProductDetailView",
            fields=[
                (
                    "category_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="posts.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
            bases=(
                lands.mixins.ObjectMixin,
                "posts.category",
                django.views.generic.base.TemplateView,
            ),
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="count",
            new_name="item_count",
        ),
    ]
