# Generated by Django 5.0 on 2023-12-27 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_product_selling_price_delete_shopproductdetailview"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 12, 27, 16, 23, 16, 622068, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
