# Generated by Django 5.0 on 2023-12-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_productreview_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="review",
            field=models.TextField(max_length=1000),
        ),
    ]
