# Generated by Django 5.0 on 2023-12-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
    ]
