# Generated by Django 5.0 on 2023-12-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_alter_product_selling_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
